export default function PrivacyPolicy() {
 return (
  <section className="max-w-3xl mx-auto w-full text-slate-800">
   <h1 className="text-3xl font-semibold mb-6">Privacy Policy</h1>
   <p className="italic mb-6">Effective starting: October 7, 2025</p>
   <p className="leading-8 mb-6">Your privacy matters to us. This privacy policy explains how Atlassian Pty Ltd, Atlassian US, Inc. and our corporate affiliates (“Atlassian”, “we”, “us”, “our”) collect, use, share, and protect your information when you use our products, services, websites, or otherwise interact with us (a list of Atlassian’s corporate affiliates can be found in the List of Subsidiaries section of Atlassian’s most recent Form 10-K, available under the SEC Filings tab by selecting the “Annual Filings” filter on the page located here). We offer a wide range of products, including our cloud and software products. We refer to all of these products, together with our other services and websites, as &quot;Services&quot; in this privacy policy.</p>
   <p className="leading-8 mb-6">This privacy policy also explains your choices surrounding how we use information about you, which includes how you can object to certain uses of information about you and how you can access and update certain information about you. <strong className="font-semibold">If you do not agree with this privacy policy, do not access or use our Services or interact with any other aspect of our business.</strong></p>
   <p className="leading-8 mb-6">For individuals in the European Economic Area, United Kingdom, or the United States: please refer to the appropriate “Regional disclosures” for additional details that may be relevant to you.</p>
   <p className="leading-8 mb-6">This privacy policy is intended to help you understand:</p>
   <ul className="list-disc space-y-2 leading-8 pl-4 mb-6">
    <li>Information we collect</li>
    <li>How we use information</li>
    <li>How we disclose information</li>
    <li>How we store and secure information</li>
    <li>How long we keep information</li>
    <li>How to access and control your information</li>
    <li>Our policy towards children</li>
    <li>Regional disclosures</li>
    <li>Changes to our privacy policy</li>
    <li>How to contact us</li>
   </ul>
   <p className="leading-8 mb-6">We offer additional policies tailored for specific audiences and use cases. These include:</p>
   <ul className="list-disc space-y-2 leading-8 pl-4 mb-6">
    <li>Cookies & Tracking Notice</li>
    <li>Atlassian Careers Privacy Notice - for job applicants</li>
    <li>Former Workplace Privacy Notice - for past employees</li>
    <li>Demographic Survery Privacy Notice - for voluntary survey data</li>
   </ul>
   <p className="leading-8 mb-12">This privacy policy describes Atlassian’s data practices as a controller of personal information. Please note that this privacy policy does not apply to the extent that we process personal information in the role of a processor or service provider on behalf of our customers, as further specified in the Data Processing Addendum entered into with those customers. When Atlassian processes personal information on behalf of our customers (such as your employer, if applicable), the customer is the controller of the personal information processed and manages those accounts and any Service sites. In such cases, Atlassian acts as a processor or service provider on behalf of our customer and handles your information according to the instructions of that organization. We are not responsible for the privacy or security practices of our customers, which may differ from those described in this privacy policy. For more information about how an Atlassian customer uses your personal information, or to exercise the rights you may have with respect to that information, please contact that organization directly.</p>
   <h2 className="text-xl font-semibold mb-6">Privacy policy overview</h2>
   <ul className="list-disc space-y-2 leading-8 pl-4 mb-12">
    <li>Atlassian collects information directly from you when you provide it to us, automatically when you use our Services, and from other sources including other users of the Services, other services you link to your account, other Atlassian companies, partners, and third-party providers.</li>
    <li>How we use information depends on which Services you use, how you use them, and any preferences you have communicated to us. We use information for a range of purposes described below, including to provide the Services and personalize your experience, to develop and improve our Services, to communicate with you, to conduct marketing and promotional activities, to provide customer support, to maintain Service safety and security, to protect our interests and rights, with your consent, and to aggregate or de-identify data.</li>
    <li>We disclose information as described below, including to service providers, Atlassian partners, providers of third-party services, for compliance with enforcement requests and applicable laws, to enforce our terms and policies and our rights, to Atlassian affiliated companies or in connection with business transfers, as well as with your consent. Additionally, when you use the Services, we disclose certain information about you to other Service users as described in more detail below.</li>
    <li>Where applicable under local law, you may have certain rights or choices with respect to your personal information, including to request information about our processing of information, to request a copy of your information, to object to our use of information, to request the deletion or restriction of information, to request a disclosure of information in a portable format, or to opt out of certain disclosures of personal information and targeted advertising. See the “How to access and control your information” section for more detail on specific choices and how to exercise the rights you may have.</li>
    <li>In the “Regional disclosures” section, we provide additional information for individuals in the European Economic Area and United Kingdom, including information about the legal bases for processing information, international transfers, the specific rights applicable in these jurisdictions, and how to contact our EU and UK representatives. We also provide additional information for individuals in the United States, including details about information collected and disclosed in the past 12 months and specific rights available under applicable U.S. state laws.</li>
    <li>We provide details on how to contact us with any questions or concerns, or to exercise your rights, in the “How to contact us” section.</li>
   </ul>
   <h2 className="text-xl font-semibold mb-6">Information we collect</h2>
   <p className="leading-8 mb-6">We collect information about you when you provide it to us, when you use our Services, and from other sources, as further described below.</p>
   <h3 className="font-semibold mb-6">Information you provide</h3>
   <p className="leading-8 mb-6">We collect information about you when you input it into the Services or otherwise provide it directly to us. This includes the following categories of information:</p>
   <p className="leading-8 mb-6"><strong className="font-semibold italic">Account Information and Profile Information:</strong> We collect information when you register for an account, create or modify your profile, set preferences, sign up for or make purchases through the Services. For example, you provide contact information (e.g., name or email address) and, in some cases, billing information (e.g., billing address, email address or name), when you register for the Services. You also have options to add a display name, profile photo, job title, and other details to your profile. We also keep track of your preferences when you select settings within the Services.</p>
   <p className="leading-8 mb-6">You may also provide information to us when you integrate or link a third-party service with our Services. For example, if you create an account or log into the Services using your Google credentials, we receive your name and email address as permitted by your Google profile settings in order to authenticate you. The information we receive when you link or integrate our Services with a third-party service depends on the settings, permissions and privacy policy controlled by that third-party service. You should always check the privacy settings and notices in these third-party services to understand what information may be disclosed to us or shared with our Services.</p>
   <p className="leading-8 mb-6"><strong className="font-semibold italic">Content you provide through our products:</strong> The Services include the Atlassian products you use, where we collect and store content that you post, send, receive and share. We process this content in the role of a processor or service provider on behalf of our customers; this privacy policy does not apply to that processing (see above for more information).</p>
   <p className="leading-8 mb-6"><strong className="font-semibold italic">Content you provide through our website:</strong> The Services also include websites owned or operated by us. We collect content that you submit to these websites, which include social media or social networking websites operated by us, our support and documentation websites, our Community Forums, and our Marketplace. For example, you provide content to us when you provide feedback, directly to us through our Services or otherwise, or when you participate in any interactive features, surveys, contests, promotions, sweepstakes, activities or events.</p>
   <p className="leading-8 mb-6"><strong className="font-semibold italic">Information you provide through our support channels:</strong> The Services also include customer support, where you may submit inquiries or other information regarding a problem you are experiencing with a Service. Whether you designate yourself as a technical contact, open a support ticket, speak to one of our representatives directly or otherwise engage with our support team or support features, you will be asked to provide contact information, a summary or description of the problem you are experiencing, and any other documentation, screenshots or information that would be helpful in resolving the issue and/or a Support Entitlement Number (SEN).</p>
   <p className="leading-8 mb-6"><strong className="font-semibold italic">Payment Information:</strong> We collect payment and billing information when you register for certain paid Services. For example, we ask you to designate a billing representative, including name and contact information, upon registration. You might also provide payment information, such as payment card details, which we collect via secure payment processing services.</p>
  </section>
 )
}